# Generated by Django 3.0.3 on 2020-05-23 16:21

from django.db import migrations, models
import get_random_quote.models


class Migration(migrations.Migration):

    dependencies = [
        ('get_random_quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=get_random_quote.models.get_image_path),
        ),
    ]
