# Generated by Django 3.0.3 on 2020-05-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_random_quote', '0003_auto_20200524_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='image',
            field=models.CharField(default='', max_length=50),
        ),
    ]
