# Generated by Django 3.0.3 on 2020-05-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_random_quote', '0004_auto_20200524_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='image_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='image',
            field=models.ImageField(upload_to='images//'),
        ),
    ]
