# Generated by Django 3.0.3 on 2020-05-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_random_quote', '0006_auto_20200524_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='photo',
        ),
        migrations.AddField(
            model_name='quote',
            name='image',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
