# Generated by Django 3.0.3 on 2020-05-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_random_quote', '0008_auto_20200524_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='Photo',
        ),
        migrations.AddField(
            model_name='quote',
            name='image',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
