# Generated by Django 3.0.3 on 2020-05-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_random_quote', '0010_auto_20200524_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='image',
        ),
        migrations.AddField(
            model_name='quote',
            name='image_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
