# Generated by Django 3.0.3 on 2020-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_random_quote', '0015_auto_20200525_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='photo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
