# Generated by Django 3.0.3 on 2020-05-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_random_quote', '0016_auto_20200525_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='photo',
            new_name='image_object',
        ),
    ]
